# Generated by Django 4.0.6 on 2022-07-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cook_time', models.CharField(choices=[('A', '0min - 30min'), ('B', '30min - 1hr'), ('C', '1hr - 2hr'), ('D', '2hr +')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrepMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep_method', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuantityUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_unit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipie_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('instructions', models.CharField(max_length=500)),
                ('cook_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cooktime')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cuisine')),
                ('diet', models.ManyToManyField(to='main.diet')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.difficulty')),
            ],
        ),
        migrations.CreateModel(
            name='RecipieIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredient')),
                ('prep_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.prepmethod')),
                ('quantity_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quantityunit')),
                ('recipie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipie')),
            ],
        ),
    ]
