# Generated by Django 4.0.6 on 2022-07-06 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='difficulty',
            options={'verbose_name': 'difficulty', 'verbose_name_plural': 'difficulties'},
        ),
        migrations.AlterField(
            model_name='cooktime',
            name='cook_time',
            field=models.CharField(choices=[('SHORTEST', '0min - 30min'), ('SHORT', '30min - 1hr'), ('LONG', '1hr - 2hr'), ('LONGEST', '2hr +')], max_length=100, verbose_name='cook time'),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='cuisine',
            field=models.CharField(max_length=100, unique=True, verbose_name='cuisine'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='diet',
            field=models.CharField(max_length=100, unique=True, verbose_name='diet'),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Beginner'), ('MEDIUM', 'Intermediate'), ('HARD', 'Advanced')], max_length=100, verbose_name='difficulty'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='ingredient'),
        ),
        migrations.AlterField(
            model_name='prepmethod',
            name='prep_method',
            field=models.CharField(max_length=100, unique=True, verbose_name='prep method'),
        ),
        migrations.AlterField(
            model_name='quantityunit',
            name='quantity_unit',
            field=models.CharField(max_length=100, unique=True, verbose_name='quantity unit'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', related_query_name='recipe', to='main.cooktime'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', related_query_name='recipe', to='main.cuisine'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', related_query_name='recipe', to='main.difficulty'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(max_length=500, verbose_name='instructions'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=100, verbose_name='recipe name'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', related_query_name='recipe_ingredient', to='main.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='prep_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', related_query_name='recipe_ingredient', to='main.prepmethod'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', related_query_name='recipe_ingredient', to='main.quantityunit'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', related_query_name='recipe_ingredient', to='main.recipe'),
        ),
    ]
