# Generated by Django 4.0.5 on 2022-07-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_recipe_description_alter_recipe_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', related_query_name='recipe', to='main.cuisine'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=models.ManyToManyField(blank=True, to='main.diet'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='prep_method',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', related_query_name='recipe_ingredient', to='main.prepmethod'),
        ),
    ]
